name: Deploy to AWS EC2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Debug SSH Configuration
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ls -la ~/.ssh
        echo "SSH key setup complete."

    - name: Ensure App Directory Exists on EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
        ${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_SSH_HOST }} "mkdir -p /home/${{ secrets.AWS_SSH_USER }}/app/vehicle-registration-backend"

    - name: Transfer Files to EC2 Instance
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r $(pwd)/ \
        ${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_SSH_HOST }}:/home/${{ secrets.AWS_SSH_USER }}/app/vehicle-registration-backend